"""
Weather Routes — Direct weather query endpoints.

REST endpoints for programmatic access (bypassing the chat/LLM layer):
  - GET /weather/current?lat=...&lon=...
  - GET /weather/forecast?lat=...&lon=...&hours=...
  - GET /weather/climatology?lat=...&lon=...&var=...&years=...
"""
